### ISSUE TITLE
node.js error

### ISSUE THREAD

**Issue by cjpoor** [johannesjo/linux-window-session-manager#1]
After installing lwsm I ran save and got the following error:
$ lwsm save
/usr/bin/env: ‘node’: No such file or directory

I tried doing install nodejs-legacy but then got 
$ lwsm save
/usr/local/lib/node_modules/linux-window-session-manager/lib/x11-wrapper.js:38
              return Promise.resolve(...arguments);
                                     ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:8:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by johannesjo** [comment]
Thank you very much for reporting. I'll check once I'm back from vacation!

**Comment by johannesjo** [comment]
Which version of node are you running?

**Comment by cjpoor** [comment]
Sorry to interrupt the vacation. Hope you are enjoying it.
Thanks for your quick reply.
$ node --version 
returns v4.2.6
which concurs with the nodejs package shown as installed by synaptic.
I could install node-debug but I wouldn't know how to use it :-\
Are there any helpers I need?

**Comment by johannesjo** [comment]
Hey there! Sorry for getting back to you so late. The issue should be fixed now also for v4.2.6, though I recommend installing a more recent version of node.

**Comment by cjpoor** [comment]
Thanks, Johannes. I updated to node v6.10.3
However, it is only shown as updated on my admin account. (I normally use a regular user account).
Can I update system-wide?

**Comment by cjpoor** [comment]
Thanks, Johannes. I updated to node v6.10.3
