### ISSUE TITLE
Error when trying to restore a session 

### ISSUE THREAD

**Issue by flccrakers** [johannesjo/linux-window-session-manager#10]
I try to use your tool, but cannot restore a session. 
I got this error: 

```
gnome-terminal-server.Gnome-terminal is running:  true 1 0
Navigator.Firefox is running:  false 1 0
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn "/usr/share/applications/firefox.desktop" ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Any idea how to fix it?
I'm using node v6.11.3

**Comment by johannesjo** [comment]
Hi there! Thanks for reporting! Is there a file at `/usr/share/applications/firefox.desktop` present?
