### ISSUE TITLE
Error while restoring: Unhandled 'error' event

### ISSUE THREAD

**Issue by miku86** [johannesjo/linux-window-session-manager#15]
I only opened Chrome and saved the state.

```
lwsm save
 0x2e00002 has no wmClassName. Win:  { windowId: ' 0x2e00002',
  windowIdDec: 48234498,
  wmCurrentDesktopNr: 0,
  wmPid: 1704,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x2e00005 has no wmClassName. Win:  { windowId: '0x2e00005',
  windowIdDec: 48234501,
  wmCurrentDesktopNr: 0,
  wmPid: 1704,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x2e00008 has no wmClassName. Win:  { windowId: '0x2e00008',
  windowIdDec: 48234504,
  wmCurrentDesktopNr: 0,
  wmPid: 1704,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x2e0000b has no wmClassName. Win:  { windowId: '0x2e0000b',
  windowIdDec: 48234507,
  wmCurrentDesktopNr: 0,
  wmPid: 1704,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x2e0000c has no wmClassName. Win:  { windowId: '0x2e0000c',
  windowIdDec: 48234508,
  wmCurrentDesktopNr: 0,
  wmPid: 1704,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
SAVED SESSION: DEFAULT
```

Then I rebooted and tried to restore it:

```
lwsm restore
 0x2e00002 has no wmClassName. Win:  { windowId: ' 0x2e00002',
  windowIdDec: 48234498,
  wmCurrentDesktopNr: 0,
  wmPid: 1704,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x2e00005 has no wmClassName. Win:  { windowId: '0x2e00005',
  windowIdDec: 48234501,
  wmCurrentDesktopNr: 0,
  wmPid: 1704,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x2e00008 has no wmClassName. Win:  { windowId: '0x2e00008',
  windowIdDec: 48234504,
  wmCurrentDesktopNr: 0,
  wmPid: 1704,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x2e0000b has no wmClassName. Win:  { windowId: '0x2e0000b',
  windowIdDec: 48234507,
  wmCurrentDesktopNr: 0,
  wmPid: 1704,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x2e0000c has no wmClassName. Win:  { windowId: '0x2e0000c',
  windowIdDec: 48234508,
  wmCurrentDesktopNr: 0,
  wmPid: 1704,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
Status: "gnome-terminal-server.Gnome-terminal" is running: true 1 0
Status: "google-chrome.Google-chrome" is running: false 1 0
Starting: "/usr/share/applications/google-chrome.desktop"
Wait for all applications to start
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn "/usr/share/applications/google-chrome.desktop" ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Michael

**Comment by johannesjo** [comment]
Thanks for reporting! I'll investigate.

**Comment by johannesjo** [comment]
Which version of lwsm are you using? Normally all windows that don't have the type `_NET_WM_WINDOW_TYPE_NORMAL` should be excluded. The window that is causing the error has the type `_NET_WM_WINDOW_TYPE_DOCK`.

**Comment by jaylenw** [comment]
Hi @johannesjo , I am encountering the same problem. I had more than just chrome opened before I saved, however, when restoring chrome was the only application out of the previously opened applications that didn't re-open. Please let me know if you would like for me to provide more information. Thank you for working on this!

linux-window-session-manager@2.1.16

```
lwsm restore
0x3c00002 has no wmClassName. Win:  { windowId: '0x3c00002',
  windowIdDec: 62914562,
  wmCurrentDesktopNr: 0,
  wmPid: 23808,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x3c00007 has no wmClassName. Win:  { windowId: '0x3c00007',
  windowIdDec: 62914567,
  wmCurrentDesktopNr: 0,
  wmPid: 23808,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x3c00011 has no wmClassName. Win:  { windowId: '0x3c00011',
  windowIdDec: 62914577,
  wmCurrentDesktopNr: 0,
  wmPid: 23808,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x3c00016 has no wmClassName. Win:  { windowId: '0x3c00016',
  windowIdDec: 62914582,
  wmCurrentDesktopNr: 0,
  wmPid: 23808,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x3c0001b has no wmClassName. Win:  { windowId: '0x3c0001b',
  windowIdDec: 62914587,
  wmCurrentDesktopNr: 0,
  wmPid: 23808,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x3c0001c has no wmClassName. Win:  { windowId: '0x3c0001c',
  windowIdDec: 62914588,
  wmCurrentDesktopNr: 0,
  wmPid: 23808,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
Status: "rambox.Rambox" is running: true 1 0
Status: "google-chrome.Google-chrome" is running: false 2 0
Starting: "/usr/share/applications/google-chrome.desktop"
Status: "google-chrome.Google-chrome" is running: false 2 0
Starting: "/usr/share/applications/google-chrome.desktop"
Status: "nautilus.Nautilus" is running: false 1 0
Starting: nautilus
Status: "terminator.Terminator" is running: true 1 0
Wait for all applications to start
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn "/usr/share/applications/google-chrome.desktop" ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by johannesjo** [comment]
Hm. Interesting! Which dock are you two using, if any and what's the output of `xprop` when you click on it?

**Comment by jaylenw** [comment]
@johannesjo I am using unity desktop on Ubuntu 16.04 latest version so the unity dock? Is that what you are referring to? As far as an error output from `xprop`, I don't recall seeing any extra errors. And honestly had to do a quick google search of `xprop` to figure out what it is. I can try and create it as soon as I can and let you know. Thanks!

**Comment by johannesjo** [comment]
ok. Afaics there shouldn't be a real issue, it's just the logging which is a little to verbose and misleading that this point. Can you confirm, that the restoring and saving behavior is working correctly?

**Comment by jaylenw** [comment]
Hi @johannesjo , I went ahead and tested `lwsm save` and `lwsm restore` again.

Before running `lwsm` save before logging out, I had chrome, slack, gedit, rambox (note: starts automatically on login by its own settings), and hp device manager (note: starts automatically on login by its own settings) in workspace 1. I also had nautilus, gnome-sushi, FAHControl, and terminator opened in workspace 2. Upon logging out and logging back in and running `lwsm restore`, the applications that opened up this time was chrome, rambox, hp device manager, and nautilus. These all opened in workspace 1.  gnome-sushi, slack, gedit, and folding@home FAHControl did not reopen in any workspace. Of course terminator would not be affected by `lwsm restore` as I had opened it manually to run `lwsm restore`. Also, gnome-sushi i believe is a special case.

linux-window-session-manager@2.1.16

Thank you.

#### Save
```
lwsm save
0x3c00002 has no wmClassName. Win:  { windowId: '0x3c00002',
  windowIdDec: 62914562,
  wmCurrentDesktopNr: 0,
  wmPid: 23808,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x3c00007 has no wmClassName. Win:  { windowId: '0x3c00007',
  windowIdDec: 62914567,
  wmCurrentDesktopNr: 0,
  wmPid: 23808,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x3c00011 has no wmClassName. Win:  { windowId: '0x3c00011',
  windowIdDec: 62914577,
  wmCurrentDesktopNr: 0,
  wmPid: 23808,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x3c00016 has no wmClassName. Win:  { windowId: '0x3c00016',
  windowIdDec: 62914582,
  wmCurrentDesktopNr: 0,
  wmPid: 23808,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x3c0001b has no wmClassName. Win:  { windowId: '0x3c0001b',
  windowIdDec: 62914587,
  wmCurrentDesktopNr: 0,
  wmPid: 23808,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x3c0001c has no wmClassName. Win:  { windowId: '0x3c0001c',
  windowIdDec: 62914588,
  wmCurrentDesktopNr: 0,
  wmPid: 23808,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
findDesktopFile cant find file; searched patterns [ '/home/jaylenw/.local/share/applications/sushi-start.desktop',
  '/home/jaylenw/.local/share/applications/**/sushi-start.desktop',
  '/home/jaylenw/.gnome/apps//sushi-start.desktop',
  '/home/jaylenw/.gnome/apps//**/sushi-start.desktop',
  '/usr/share/applications/sushi-start.desktop',
  '/usr/share/applications/**/sushi-start.desktop',
  '/usr/local/share/applications/sushi-start.desktop',
  '/usr/local/share/applications/**/sushi-start.desktop',
  '/usr/share/app-install/sushi-start.desktop',
  '/usr/share/app-install/**/sushi-start.desktop',
  '/home/jaylenw/.config/autostart//sushi-start.desktop',
  '/home/jaylenw/.config/autostart//**/sushi-start.desktop' ]
util: Generic Error findDesktopFile cant find file; searched patterns undefined
util: { '0': 'findDesktopFile cant find file; searched patterns' }
Input Handler Error:  No input for desktop file path for window "sushi-start.Sushi-start". Please fix this manually in config file for this session in ~/.lwsm/session-name.json undefined
SAVED SESSION: DEFAULT
```

#### Restore

```
lwsm restore
 0x1e00002 has no wmClassName. Win:  { windowId: ' 0x1e00002',
  windowIdDec: 31457282,
  wmCurrentDesktopNr: 0,
  wmPid: 31582,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x1e00007 has no wmClassName. Win:  { windowId: '0x1e00007',
  windowIdDec: 31457287,
  wmCurrentDesktopNr: 0,
  wmPid: 31582,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x1e00011 has no wmClassName. Win:  { windowId: '0x1e00011',
  windowIdDec: 31457297,
  wmCurrentDesktopNr: 0,
  wmPid: 31582,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x1e00016 has no wmClassName. Win:  { windowId: '0x1e00016',
  windowIdDec: 31457302,
  wmCurrentDesktopNr: 0,
  wmPid: 31582,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x1e0001b has no wmClassName. Win:  { windowId: '0x1e0001b',
  windowIdDec: 31457307,
  wmCurrentDesktopNr: 0,
  wmPid: 31582,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
0x1e0001c has no wmClassName. Win:  { windowId: '0x1e0001c',
  windowIdDec: 31457308,
  wmCurrentDesktopNr: 0,
  wmPid: 31582,
  wmType: '_NET_WM_WINDOW_TYPE_DOCK',
  states: 
   [ '_NET_WM_STATE_STICKY',
     '_NET_WM_STATE_SKIP_TASKBAR',
     '_NET_WM_STATE_SKIP_PAGER' ] }
Status: "rambox.Rambox" is running: true 1 0
Status: "nautilus.Nautilus" is running: false 1 0
Starting: nautilus
Status: "google-chrome.Google-chrome" is running: false 2 0
Starting: google-chrome.desktop
Status: "google-chrome.Google-chrome" is running: false 2 0
Starting: google-chrome.desktop
Status: "slack.Slack" is running: false 1 0
Starting: "/usr/share/applications/slack.desktop"
Status: "gedit.Gedit" is running: false 1 0
Starting: "/usr/share/applications/gedit.desktop"
Status: "remmina.Remmina" is running: false 1 0
Starting: "/usr/share/applications/remmina.desktop"
Status: "FAHControl.FAHControl" is running: false 1 0
Starting: "/usr/share/applications/FAHControl.desktop"
Status: "terminator.Terminator" is running: true 1 0
Status: "sushi-start.Sushi-start" is running: false 1 0
Starting: sushi-start.desktop
Wait for all applications to start
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn "/usr/share/applications/slack.desktop" ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by johannesjo** [comment]
@jaylenw: I added a troubleshooting section to the README.md. Could you please check if the information helps to solve your problem?

**Comment by jaylenw** [comment]
Hey @johannesjo , thanks, I will check it out when i get the chance.

**Comment by jaylenw** [comment]
Hi @johannesjo , Thanks again for working on this. I have read over the REAME troubleshooting section and I think those changes should work. `gnome-sushi` is a weird program in itself and Slack being an `electron` application could be doing something differently than normal gnome applications.

**Comment by johannesjo** [comment]
I'm glad that it works! Electron applications sometimes do work. You can find out more about a program by executing `xprop` and clicking on the application window, there you should be able to find the data required to manually add it to your global configuration.
