### ISSUE TITLE
Error while restoring: Cannot read property windowId of undefined

### ISSUE THREAD

**Issue by Gilthans** [johannesjo/linux-window-session-manager#16]
Hey,
I've tried running lwsm save just before rebooting, and then lwsm restore.
The save worked, and the restore opened the old windows, but then didn't put them into their place. The command line showed the following error:
```
Status: "google-chrome.Google-chrome" is running: false 8 0
Starting: google-chrome.desktop
Status: "google-chrome.Google-chrome" is running: false 8 0
Starting: google-chrome.desktop
Status: "google-chrome.Google-chrome" is running: false 8 0
Starting: google-chrome.desktop
Status: "google-chrome.Google-chrome" is running: false 8 0
Starting: google-chrome.desktop
Status: "google-chrome.Google-chrome" is running: false 8 0
Starting: google-chrome.desktop
Status: "gnome-terminal.Gnome-terminal" is running: false 4 0
Starting: gnome-terminal.desktop
Status: "nautilus.Nautilus" is running: false 1 0
Starting: nautilus
Status: "google-chrome.Google-chrome" is running: false 8 0
Starting: google-chrome.desktop
Status: "google-chrome.Google-chrome" is running: false 8 0
Starting: google-chrome.desktop
Status: "google-chrome.Google-chrome" is running: false 8 0
Starting: google-chrome.desktop
Status: "gnome-terminal.Gnome-terminal" is running: false 4 0
Starting: gnome-terminal.desktop
Status: "gnome-terminal.Gnome-terminal" is running: false 4 0
Starting: gnome-terminal.desktop
Status: "gedit.Gedit" is running: false 1 0
Starting: gedit.desktop
Status: "gnome-terminal.Gnome-terminal" is running: false 4 0
Starting: gnome-terminal.desktop
Wait for all applications to start
All applications started
An error occurred TypeError: Cannot read property 'windowId' of undefined
    at savedWindowList.forEach (/usr/local/lib/node_modules/linux-window-session-manager/lib/index.js:444:55)
    at Array.forEach (<anonymous>)
    at updateWindowIds (/usr/local/lib/node_modules/linux-window-session-manager/lib/index.js:439:19)
    at closeAllWindowsIfSet.then.then.then.then.then.then (/usr/local/lib/node_modules/linux-window-session-manager/lib/index.js:205:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Generic Error in Main Handler TypeError: Cannot read property 'windowId' of undefined
    at savedWindowList.forEach (/usr/local/lib/node_modules/linux-window-session-manager/lib/index.js:444:55)
    at Array.forEach (<anonymous>)
    at updateWindowIds (/usr/local/lib/node_modules/linux-window-session-manager/lib/index.js:439:19)
    at closeAllWindowsIfSet.then.then.then.then.then.then (/usr/local/lib/node_modules/linux-window-session-manager/lib/index.js:205:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) TypeError: Cannot read property 'windowId' of undefined
    at savedWindowList.forEach (/usr/local/lib/node_modules/linux-window-session-manager/lib/index.js:444:55)
    at Array.forEach (<anonymous>)
    at updateWindowIds (/usr/local/lib/node_modules/linux-window-session-manager/lib/index.js:439:19)
    at closeAllWindowsIfSet.then.then.then.then.then.then (/usr/local/lib/node_modules/linux-window-session-manager/lib/index.js:205:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:7925) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'windowId' of undefined
(node:7925) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I am using node v8.9.1 on Ubuntu 14 with Unity.

The session file looks like this:
```
{
  "name": "DEFAULT",
  "displaysCombinations": [
    {
      "id": "1920x1200;1920x1200",
      "windowList": [
        {
          "windowId": " 0x2e00017",
          "windowIdDec": 48234519,
          "states": [
            "_NET_WM_STATE_MAXIMIZED_HORZ",
            "_NET_WM_STATE_MAXIMIZED_VERT"
          ],
          "wmCurrentDesktopNr": 0,
          "wmTitle": "\"STTCacheDashboard:copy_stt_config.borgcron.borg - Cider - Google Chrome\"",
          "wmClassName": "google-chrome.Google-chrome",
          "wmType": "_NET_WM_WINDOW_TYPE_NORMAL",
          "wmPid": 139287,
          "x": 0,
          "y": 0,
          "width": 1920,
          "height": 1174,
          "simpleName": "Google-chrome",
          "executableFile": "google-chrome.desktop",
          "desktopFilePath": "/usr/share/applications/google-chrome.desktop"
        },
        {
          "windowId": "0x2e00018",
          "windowIdDec": 48234520,
          "states": [
            "_NET_WM_STATE_MAXIMIZED_HORZ",
            "_NET_WM_STATE_MAXIMIZED_VERT"
          ],
          "wmCurrentDesktopNr": 0,
          "wmTitle": "\"https://cnsviewer2.corp.google.com/cns/ql-d/home/blue-ginger-prod/stt_cache/active_cache.json - Google Chrome\"",
          "wmClassName": "google-chrome.Google-chrome",
          "wmType": "_NET_WM_WINDOW_TYPE_NORMAL",
          "wmPid": 139287,
          "x": 1920,
          "y": 0,
          "width": 1920,
          "height": 1200,
          "simpleName": "Google-chrome",
          "executableFile": "google-chrome.desktop",
          "desktopFilePath": "/usr/share/applications/google-chrome.desktop"
        },
        {
          "windowId": "0x2e00019",
          "windowIdDec": 48234521,
          "states": [
            "_NET_WM_STATE_MAXIMIZED_HORZ",
            "_NET_WM_STATE_MAXIMIZED_VERT"
          ],
          "wmCurrentDesktopNr": 2,
          "wmTitle": "\"(9) Jayceeoh - Elevate ft. Nevve (Mashd N Kutcher Remix) - YouTube - Google Chrome\"",
          "wmClassName": "google-chrome.Google-chrome",
          "wmType": "_NET_WM_WINDOW_TYPE_NORMAL",
          "wmPid": 139287,
          "x": 1920,
          "y": 0,
          "width": 1920,
          "height": 1200,
          "simpleName": "Google-chrome",
          "executableFile": "google-chrome.desktop",
          "desktopFilePath": "/usr/share/applications/google-chrome.desktop"
        },
        {
          "windowId": "0x2e0001a",
          "windowIdDec": 48234522,
          "states": [
            "_NET_WM_STATE_MAXIMIZED_HORZ",
            "_NET_WM_STATE_MAXIMIZED_VERT"
          ],
          "wmCurrentDesktopNr": 1,
          "wmTitle": "\"Untitled Script - #plx - Google Chrome\"",
          "wmClassName": "google-chrome.Google-chrome",
          "wmType": "_NET_WM_WINDOW_TYPE_NORMAL",
          "wmPid": 139287,
          "x": 1920,
          "y": 0,
          "width": 1920,
          "height": 1200,
          "simpleName": "Google-chrome",
          "executableFile": "google-chrome.desktop",
          "desktopFilePath": "/usr/share/applications/google-chrome.desktop"
        },
        {
          "windowId": "0x2e00422",
          "windowIdDec": 48235554,
          "states": [
            "_NET_WM_STATE_MAXIMIZED_HORZ",
            "_NET_WM_STATE_MAXIMIZED_VERT"
          ],
          "wmCurrentDesktopNr": 3,
          "wmTitle": "\"BG Player - Google Chrome\"",
          "wmClassName": "google-chrome.Google-chrome",
          "wmType": "_NET_WM_WINDOW_TYPE_NORMAL",
          "wmPid": 139287,
          "x": 0,
          "y": 0,
          "width": 1920,
          "height": 1174,
          "simpleName": "Google-chrome",
          "executableFile": "google-chrome.desktop",
          "desktopFilePath": "/usr/share/applications/google-chrome.desktop"
        },
        {
          "windowId": "0x3a0000c",
          "windowIdDec": 60817420,
          "states": [],
          "wmCurrentDesktopNr": 3,
          "wmType": "_NET_WM_WINDOW_TYPE_NORMAL",
          "wmPid": 58386,
          "wmClassName": "gnome-terminal.Gnome-terminal",
          "x": 2295,
          "y": 200,
          "width": 1186,
          "height": 653,
          "simpleName": "Gnome-terminal",
          "executableFile": "gnome-terminal.desktop",
          "desktopFilePath": "/usr/share/applications/gnome-terminal.desktop"
        },
        {
          "windowId": "0x3c0003c",
          "windowIdDec": 62914620,
          "states": [],
          "wmCurrentDesktopNr": 3,
          "wmType": "_NET_WM_WINDOW_TYPE_NORMAL",
          "wmPid": 58941,
          "wmClassName": "nautilus.Nautilus",
          "x": 525,
          "y": 358,
          "width": 855,
          "height": 550,
          "simpleName": "Nautilus",
          "executableFile": "nautilus"
        },
        {
          "windowId": "0x2e004dd",
          "windowIdDec": 48235741,
          "states": [
            "_NET_WM_STATE_MAXIMIZED_HORZ",
            "_NET_WM_STATE_MAXIMIZED_VERT"
          ],
          "wmCurrentDesktopNr": 1,
          "wmTitle": "\"Add PLX scripts to monitor the active STT Cache - CL 178758366 - Google Chrome\"",
          "wmClassName": "google-chrome.Google-chrome",
          "wmType": "_NET_WM_WINDOW_TYPE_NORMAL",
          "wmPid": 139287,
          "x": 0,
          "y": 0,
          "width": 1920,
          "height": 1174,
          "simpleName": "Google-chrome",
          "executableFile": "google-chrome.desktop",
          "desktopFilePath": "/usr/share/applications/google-chrome.desktop"
        },
        {
          "windowId": "0x2e008a8",
          "windowIdDec": 48236712,
          "states": [
            "_NET_WM_STATE_MAXIMIZED_HORZ",
            "_NET_WM_STATE_MAXIMIZED_VERT"
          ],
          "wmCurrentDesktopNr": 4,
          "wmTitle": "\"servomatic_tests.ipynb - Colaboratory - Google Chrome\"",
          "wmClassName": "google-chrome.Google-chrome",
          "wmType": "_NET_WM_WINDOW_TYPE_NORMAL",
          "wmPid": 139287,
          "x": 0,
          "y": 0,
          "width": 1920,
          "height": 1174,
          "simpleName": "Google-chrome",
          "executableFile": "google-chrome.desktop",
          "desktopFilePath": "/usr/share/applications/google-chrome.desktop"
        },
        {
          "windowId": "0x2e008b8",
          "windowIdDec": 48236728,
          "states": [
            "_NET_WM_STATE_MAXIMIZED_HORZ",
            "_NET_WM_STATE_MAXIMIZED_VERT"
          ],
          "wmCurrentDesktopNr": 4,
          "wmTitle": "\"TFX:extract_intent.py - Cider - Google Chrome\"",
          "wmClassName": "google-chrome.Google-chrome",
          "wmType": "_NET_WM_WINDOW_TYPE_NORMAL",
          "wmPid": 139287,
          "x": 1920,
          "y": 0,
          "width": 1920,
          "height": 1200,
          "simpleName": "Google-chrome",
          "executableFile": "google-chrome.desktop",
          "desktopFilePath": "/usr/share/applications/google-chrome.desktop"
        },
        {
          "windowId": "0x3a1c97c",
          "windowIdDec": 60934524,
          "states": [
            "_NET_WM_STATE_MAXIMIZED_HORZ",
            "_NET_WM_STATE_MAXIMIZED_VERT",
            "_NET_WM_STATE_HIDDEN"
          ],
          "wmCurrentDesktopNr": 4,
          "wmType": "_NET_WM_WINDOW_TYPE_NORMAL",
          "wmPid": 58386,
          "wmClassName": "gnome-terminal.Gnome-terminal",
          "x": 1920,
          "y": 28,
          "width": 1920,
          "height": 1172,
          "simpleName": "Gnome-terminal",
          "executableFile": "gnome-terminal.desktop",
          "desktopFilePath": "/usr/share/applications/gnome-terminal.desktop"
        },
        {
          "windowId": "0x3a24f00",
          "windowIdDec": 60968704,
          "states": [],
          "wmCurrentDesktopNr": 4,
          "wmType": "_NET_WM_WINDOW_TYPE_NORMAL",
          "wmPid": 58386,
          "wmClassName": "gnome-terminal.Gnome-terminal",
          "x": 2435,
          "y": 282,
          "width": 1186,
          "height": 653,
          "simpleName": "Gnome-terminal",
          "executableFile": "gnome-terminal.desktop",
          "desktopFilePath": "/usr/share/applications/gnome-terminal.desktop"
        },
        {
          "windowId": "0x3000029",
          "windowIdDec": 50331689,
          "states": [],
          "wmCurrentDesktopNr": 4,
          "wmType": "_NET_WM_WINDOW_TYPE_NORMAL",
          "wmPid": 51633,
          "wmClassName": "gedit.Gedit",
          "x": 626,
          "y": 355,
          "width": 650,
          "height": 500,
          "simpleName": "Gedit",
          "executableFile": "gedit.desktop",
          "desktopFilePath": "/usr/share/applications/gedit.desktop"
        },
        {
          "windowId": "0x3aca32a\n",
          "windowIdDec": 61645610,
          "states": [
            "_NET_WM_STATE_FOCUSED"
          ],
          "wmCurrentDesktopNr": 0,
          "wmType": "_NET_WM_WINDOW_TYPE_NORMAL",
          "wmPid": 58386,
          "wmClassName": "gnome-terminal.Gnome-terminal",
          "x": 500,
          "y": 378,
          "width": 1186,
          "height": 653,
          "simpleName": "Gnome-terminal",
          "executableFile": "gnome-terminal.desktop",
          "desktopFilePath": "/usr/share/applications/gnome-terminal.desktop"
        }
      ]
    }
  ]
}
```

**Comment by johannesjo** [comment]
Hello! Thanks for reporting! I'll look into it. Looks like a hick up of some sort. You should probably be able to solve this by saving the session once more.
