### ISSUE TITLE
utility.js SyntaxError

### ISSUE THREAD

**Issue by marco-games** [johannesjo/linux-window-session-manager#17]
When running:
`$ lwsm save`

I get an error:
```
/usr/local/lib/node_modules/linux-window-session-manager/lib/utility.js:12
let CFG;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:12:20)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

Nodejs version: 4.2.6

**Comment by johannesjo** [comment]
Hey! Thanks for reporting. Updating your node version will probably help.

**Comment by marco-games** [comment]
Upgrading to 8.9.4 fixed the issue but now I cannot install npm due to held broken packages.

**Comment by johannesjo** [comment]
Does this help: https://askubuntu.com/questions/899756/cant-install-npm-unable-to-correct-problems-you-have-held-broken-packages/978353 
?

**Comment by marco-games** [comment]
Aptitude gives me two options:

1. not installing npm
2. downgrading nodejs

**Comment by johannesjo** [comment]
Hey there could be a couple of reasons. I would suggest you search stackoverflow and Google for a solution.
