### ISSUE TITLE
fs is not defined

### ISSUE THREAD

**Issue by DasLampe** [johannesjo/linux-window-session-manager#28]
```
$ lwsm save
/usr/local/lib/node_modules/linux-window-session-manager/lib/utility.js:57
      throw err;
      ^

ReferenceError: fs is not defined
    at Object.mkdirSync (/usr/local/lib/node_modules/linux-window-session-manager/lib/utility.js:54:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/linux-window-session-manager/lib/index.js:33:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```
Steps before:
```
$ apt-get install npm
[...]
$ sudo npm install -g linux-window-session-manager
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/bin/lwsm -> /usr/local/lib/node_modules/linux-window-session-manager/cmd.js
/usr/local/lib
└─┬ linux-window-session-manager@2.1.22 
  ├─┬ findup-sync@2.0.0 
  │ ├── detect-file@1.0.0 
  │ ├─┬ is-glob@3.1.0 
  │ │ └── is-extglob@2.1.1 
  │ ├─┬ micromatch@3.1.10 
  │ │ ├── arr-diff@4.0.0 
  │ │ ├── array-unique@0.3.2 
  │ │ ├─┬ braces@2.3.2 
  │ │ │ ├── arr-flatten@1.1.0 
  │ │ │ ├─┬ extend-shallow@2.0.1 
  │ │ │ │ └── is-extendable@0.1.1 
  │ │ │ ├─┬ fill-range@4.0.0 
  │ │ │ │ ├── extend-shallow@2.0.1 
  │ │ │ │ ├─┬ is-number@3.0.0 
  │ │ │ │ │ └─┬ kind-of@3.2.2 
  │ │ │ │ │   └── is-buffer@1.1.6 
  │ │ │ │ ├── repeat-string@1.6.1 
  │ │ │ │ └── to-regex-range@2.1.1 
  │ │ │ ├── isobject@3.0.1 
  │ │ │ ├── repeat-element@1.1.3 
  │ │ │ ├─┬ snapdragon-node@2.1.1 
  │ │ │ │ ├─┬ define-property@1.0.0 
  │ │ │ │ │ └─┬ is-descriptor@1.0.2 
  │ │ │ │ │   ├── is-accessor-descriptor@1.0.0 
  │ │ │ │ │   └── is-data-descriptor@1.0.0 
  │ │ │ │ └─┬ snapdragon-util@3.0.1 
  │ │ │ │   └── kind-of@3.2.2 
  │ │ │ └── split-string@3.1.0 
  │ │ ├─┬ define-property@2.0.2 
  │ │ │ └─┬ is-descriptor@1.0.2 
  │ │ │   ├── is-accessor-descriptor@1.0.0 
  │ │ │   └── is-data-descriptor@1.0.0 
  │ │ ├─┬ extend-shallow@3.0.2 
  │ │ │ ├── assign-symbols@1.0.0 
  │ │ │ └─┬ is-extendable@1.0.1 
  │ │ │   └── is-plain-object@2.0.4 
  │ │ ├─┬ extglob@2.0.4 
  │ │ │ ├─┬ define-property@1.0.0 
  │ │ │ │ └─┬ is-descriptor@1.0.2 
  │ │ │ │   ├── is-accessor-descriptor@1.0.0 
  │ │ │ │   └── is-data-descriptor@1.0.0 
  │ │ │ ├─┬ expand-brackets@2.1.4 
  │ │ │ │ ├── define-property@0.2.5 
  │ │ │ │ ├── extend-shallow@2.0.1 
  │ │ │ │ └── posix-character-classes@0.1.1 
  │ │ │ └── extend-shallow@2.0.1 
  │ │ ├─┬ fragment-cache@0.2.1 
  │ │ │ └── map-cache@0.2.2 
  │ │ ├── kind-of@6.0.2 
  │ │ ├─┬ nanomatch@1.2.13 
  │ │ │ └── is-windows@1.0.2 
  │ │ ├── object.pick@1.3.0 
  │ │ ├─┬ regex-not@1.0.2 
  │ │ │ └─┬ safe-regex@1.1.0 
  │ │ │   └── ret@0.1.15 
  │ │ ├─┬ snapdragon@0.8.2 
  │ │ │ ├─┬ base@0.11.2 
  │ │ │ │ ├─┬ cache-base@1.0.1 
  │ │ │ │ │ ├─┬ collection-visit@1.0.0 
  │ │ │ │ │ │ ├── map-visit@1.0.0 
  │ │ │ │ │ │ └── object-visit@1.0.1 
  │ │ │ │ │ ├── get-value@2.0.6 
  │ │ │ │ │ ├─┬ has-value@1.0.0 
  │ │ │ │ │ │ └─┬ has-values@1.0.0 
  │ │ │ │ │ │   └── kind-of@4.0.0 
  │ │ │ │ │ ├─┬ set-value@2.0.0 
  │ │ │ │ │ │ └── extend-shallow@2.0.1 
  │ │ │ │ │ ├─┬ to-object-path@0.3.0 
  │ │ │ │ │ │ └── kind-of@3.2.2 
  │ │ │ │ │ ├─┬ union-value@1.0.0 
  │ │ │ │ │ │ └─┬ set-value@0.4.3 
  │ │ │ │ │ │   └── extend-shallow@2.0.1 
  │ │ │ │ │ └─┬ unset-value@1.0.0 
  │ │ │ │ │   └─┬ has-value@0.3.1 
  │ │ │ │ │     ├── has-values@0.1.4 
  │ │ │ │ │     └─┬ isobject@2.1.0 
  │ │ │ │ │       └── isarray@1.0.0 
  │ │ │ │ ├─┬ class-utils@0.3.6 
  │ │ │ │ │ ├── arr-union@3.1.0 
  │ │ │ │ │ ├── define-property@0.2.5 
  │ │ │ │ │ └─┬ static-extend@0.1.2 
  │ │ │ │ │   ├── define-property@0.2.5 
  │ │ │ │ │   └─┬ object-copy@0.1.0 
  │ │ │ │ │     ├── copy-descriptor@0.1.1 
  │ │ │ │ │     ├── define-property@0.2.5 
  │ │ │ │ │     └── kind-of@3.2.2 
  │ │ │ │ ├── component-emitter@1.2.1 
  │ │ │ │ ├─┬ define-property@1.0.0 
  │ │ │ │ │ └─┬ is-descriptor@1.0.2 
  │ │ │ │ │   ├── is-accessor-descriptor@1.0.0 
  │ │ │ │ │   └── is-data-descriptor@1.0.0 
  │ │ │ │ ├─┬ mixin-deep@1.3.1 
  │ │ │ │ │ ├── for-in@1.0.2 
  │ │ │ │ │ └── is-extendable@1.0.1 
  │ │ │ │ └── pascalcase@0.1.1 
  │ │ │ ├─┬ debug@2.6.9 
  │ │ │ │ └── ms@2.0.0 
  │ │ │ ├─┬ define-property@0.2.5 
  │ │ │ │ └─┬ is-descriptor@0.1.6 
  │ │ │ │   ├─┬ is-accessor-descriptor@0.1.6 
  │ │ │ │   │ └── kind-of@3.2.2 
  │ │ │ │   ├─┬ is-data-descriptor@0.1.4 
  │ │ │ │   │ └── kind-of@3.2.2 
  │ │ │ │   └── kind-of@5.1.0 
  │ │ │ ├── extend-shallow@2.0.1 
  │ │ │ ├── source-map@0.5.7 
  │ │ │ ├─┬ source-map-resolve@0.5.2 
  │ │ │ │ ├── atob@2.1.2 
  │ │ │ │ ├── decode-uri-component@0.2.0 
  │ │ │ │ ├── resolve-url@0.2.1 
  │ │ │ │ ├── source-map-url@0.4.0 
  │ │ │ │ └── urix@0.1.0 
  │ │ │ └── use@3.1.1 
  │ │ └── to-regex@3.0.2 
  │ └─┬ resolve-dir@1.0.1 
  │   ├─┬ expand-tilde@2.0.2 
  │   │ └─┬ homedir-polyfill@1.0.1 
  │   │   └── parse-passwd@1.0.0 
  │   └─┬ global-modules@1.0.0 
  │     └─┬ global-prefix@1.0.2 
  │       ├── ini@1.3.5 
  │       └─┬ which@1.3.1 
  │         └── isexe@2.0.0 
  ├─┬ jfs@0.2.6 
  │ ├── async@1.2.1 
  │ ├── clone@1.0.4 
  │ ├─┬ mkdirp@0.5.1 
  │ │ └── minimist@0.0.8 
  │ └── node-uuid@1.4.8 
  ├── omelette@0.4.11 
  ├─┬ promise-waterfall@0.1.0 
  │ └─┬ promise@6.0.1 
  │   └── asap@1.0.0 
  └─┬ x11@2.3.0 
    └── os-homedir@1.0.2 
``` 

* Ubuntu Mate 18.04
* npm --version: 3.5.2

**Comment by johannesjo** [comment]
Hey! Thanks for reporting! A new version is available which should fix this issue.
