### ISSUE TITLE
Doesn't work with Brave Browser-created "Chrome" apps

### ISSUE THREAD

**Issue by wizonesolutions** [johannesjo/linux-window-session-manager#41]
## Your Environment

* Version used: 2.1.28
* Operating System and version: Ubuntu Linux 18.04
* Desktop Environment: Default (GNOME 3?)
* Node version: v8.10.0

## Expected Behavior

"Apps" created by using _More tools -> Create shortcut_ in Brave should be saved properly.

## Current Behavior

This happens:

````
$ lwsm save
findDesktopFile cant find file; searched patterns [ '/home/kevin/.local/share/applications/*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop',
  '/home/kevin/.local/share/applications/**/*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop',
  '/home/kevin/.gnome/apps//*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop',
  '/home/kevin/.gnome/apps//**/*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop',
  '/usr/share/applications/*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop',
  '/usr/share/applications/**/*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop',
  '/usr/local/share/applications/*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop',
  '/usr/local/share/applications/**/*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop',
  '/usr/share/app-install/*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop',
  '/usr/share/app-install/**/*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop',
  '/home/kevin/.config/autostart//*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop',
  '/home/kevin/.config/autostart//**/*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop',
  '/var/lib/snapd/desktop/applications/*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop',
  '/var/lib/snapd/desktop/applications/**/*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop',
  '/var/lib/flatpak/app/*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop',
  '/var/lib/flatpak/app/**/*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop',
  '/snap/bin/*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop',
  '/snap/bin/**/*chrome-pofoocnjclhmhkhkgibipddgekdlnfmj*.desktop' ]
util: Generic Error findDesktopFile cant find file; searched patterns undefined
util: { '0': 'findDesktopFile cant find file; searched patterns' }
Generic Error in Meta Wrapper TypeError: Cannot read property 'split' of undefined
    at findDesktopFile.then (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:194:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) TypeError: Cannot read property 'split' of undefined
    at findDesktopFile.then (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:194:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Generic Error in Meta Wrapper TypeError: Cannot read property 'split' of undefined
    at findDesktopFile.then (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:194:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) TypeError: Cannot read property 'split' of undefined
    at findDesktopFile.then (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:194:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Generic Error in Meta Wrapper TypeError: Cannot read property 'split' of undefined
    at findDesktopFile.then (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:194:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) TypeError: Cannot read property 'split' of undefined
    at findDesktopFile.then (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:194:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:31016) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at findDesktopFile.then (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:194:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:31016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:31016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

## Steps to Reproduce (for bugs)

1. Install Brave Browser from https://brave.com/download/
2. Go to any site. http://example.com will do
3. Click the menu under the minimize/maximize/close buttons at the top-right of the window
4. Under "More tools", click "Create shortcut" and choose "Open as window" in the dialog that pops up.
5. Once done, ensure the app is open and try `lwsm save`.

## Notes

The issue is that Brave saves the files with a `brave-` prefix instead of a `chrome-` one. So you need to check `WM_CLASS(STRING)` for something like:

`WM_CLASS(STRING) = "crx_hppgbgfhlaeddfkdifgnpndnccffohpn", "Brave-browser"`

Here we see `"Brave-browser"` in the second position. It wasn't immediately clear to me how to modify the program to do this, since by that point in the pipeline we're already dealing with a filename, and I wasn't sure if the `WM_CLASS` value was still in scope anywhere.

Example Brave filename: `/home/kevin/.local/share/applications/brave-ddiddklncfgbfaaahngklemobghhjkim-Default.desktop`

I can work around this by just changing the prefix manually. It doesn't seem to break the apps (haven't tried uninstalling one yet; unsure if it would fail to clean up the desktop file).

**Comment by johannesjo** [comment]
Thanks for opening up this issue (and actually taking the time to fill out all the required information, people tend to forget ;)).

I'm pretty busy for the next weeks, but will probably check the one after that. Please remind me if I forget.

**Comment by johannesjo** [comment]
The issue should hopefully be fixed now.

**Comment by wizonesolutions** [comment]
Thanks! Unfortunately, it seems to persist :/

```
$ sudo npm install -g linux-window-session-manager
[sudo] password for kevin: 
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/usr/local/bin/lwsm -> /usr/local/lib/node_modules/linux-window-session-manager/cmd.js
/usr/local/lib
└─┬ linux-window-session-manager@2.1.30 
  └─┬ findup-sync@3.0.0 
    └── is-glob@4.0.1 

$ rm ~/.lwsm/config.json
$ lwsm save
lwsm: no config file present or it contains invalid json. Creating new one...
Generic Error in Meta Wrapper TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.basename (path.js:1380:5)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:193:18)
    at new Promise (<anonymous>)
    at parseChromeAppDesktopFileName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:190:10)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:166:9)
    at new Promise (<anonymous>)
    at parseExecutableFileFromWmClassName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:158:10)
    at promises.push (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:136:18)
    at <anonymous> TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.basename (path.js:1380:5)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:193:18)
    at new Promise (<anonymous>)
    at parseChromeAppDesktopFileName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:190:10)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:166:9)
    at new Promise (<anonymous>)
    at parseExecutableFileFromWmClassName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:158:10)
    at promises.push (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:136:18)
    at <anonymous>
Generic Error in Meta Wrapper TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.basename (path.js:1380:5)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:193:18)
    at new Promise (<anonymous>)
    at parseChromeAppDesktopFileName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:190:10)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:166:9)
    at new Promise (<anonymous>)
    at parseExecutableFileFromWmClassName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:158:10)
    at promises.push (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:136:18)
    at <anonymous> TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.basename (path.js:1380:5)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:193:18)
    at new Promise (<anonymous>)
    at parseChromeAppDesktopFileName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:190:10)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:166:9)
    at new Promise (<anonymous>)
    at parseExecutableFileFromWmClassName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:158:10)
    at promises.push (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:136:18)
    at <anonymous>
Generic Error in Meta Wrapper TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.basename (path.js:1380:5)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:193:18)
    at new Promise (<anonymous>)
    at parseChromeAppDesktopFileName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:190:10)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:166:9)
    at new Promise (<anonymous>)
    at parseExecutableFileFromWmClassName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:158:10)
    at promises.push (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:136:18)
    at <anonymous> TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.basename (path.js:1380:5)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:193:18)
    at new Promise (<anonymous>)
    at parseChromeAppDesktopFileName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:190:10)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:166:9)
    at new Promise (<anonymous>)
    at parseExecutableFileFromWmClassName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:158:10)
    at promises.push (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:136:18)
    at <anonymous>
(node:440) UnhandledPromiseRejectionWarning: TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.basename (path.js:1380:5)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:193:18)
    at new Promise (<anonymous>)
    at parseChromeAppDesktopFileName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:190:10)
    at Promise (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:166:9)
    at new Promise (<anonymous>)
    at parseExecutableFileFromWmClassName (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:158:10)
    at promises.push (/usr/local/lib/node_modules/linux-window-session-manager/lib/metaWrapper.js:136:18)
    at <anonymous>
(node:440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

No more detail than this. Can I do anything to diagnose?

**Comment by johannesjo** [comment]
Oh!! This is... interesting. :) I'll check this tomorrow!

**Comment by johannesjo** [comment]
Hopefully this is fixed now. Thanks for getting back to me!

**Comment by wizonesolutions** [comment]
Nice, getting closer. I may have to manually map some other apps (or submit PRs, since I see you include quite a few in the default `config.json`), but in any case I will try to remember to turn back on the GNOME extension that uses this before I restart and see how it goes :) thanks for the quick replies!

**Comment by johannesjo** [comment]
PR for default apps would be welcome. I personally only use a handful of apps regularly, so there are probably a lot of special cases missing!

**Comment by wizonesolutions** [comment]
Seems OK now. I ran into another quirk that is separate; will open issue.
