### ISSUE TITLE
only works if gnome-terminal is already open @ Ubuntu 19.10

### ISSUE THREAD

**Issue by electricimp123** [johannesjo/linux-window-session-manager#50]
## Your Environment

* Version used: can't tell
* Operating System and version: Ubuntu 19.10
* Desktop Environment: Gnome 3.34.1
* Node version: 12.13.0
* List of Applications that are open (lwsm save) or should be opened (lwsm restore):
gnome-terminal-server.Gnome-terminal
atom.Atom
Navigator.Firefox

## Expected Behavior

applications should be opened and placed regardless of whether a gnome terminal is already open or not.  /var/syslog shows this:

gnome-shell[1601]: Status: "gnome-terminal-server.Gnome-terminal" is running: true 1 0
gnome-shell[1601]: Status: "atom.Atom" is running: false 1 0
gnome-shell[1601]: Status: "Navigator.Firefox" is running: false 1 0
gnome-shell[1601]: Waiting for all applications to start...
gnome-shell[1601]: All applications started
gnome-shell[1601]: Restoring window position for "gnome-terminal-server.Gnome-terminal"
gnome-shell[1601]: Restoring window position for "atom.Atom"
gnome-shell[1601]: Restoring window position for "Navigator.Firefox"
gnome-shell[1601]: RESTORED SESSION: TestSession

## Current Behavior

applications are opened and placed ONLY if a gnome terminal is already open.  otherwise, /var/syslog has the following error:

gnome-shell[1601]: { Error: Bad window
gnome-shell[1601]:     at ReadFixedRequest.callback (/home/electricimp123/.nvm/versions/node/v12.13.0/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/xcore.js:465:29)
gnome-shell[1601]:     at ReadFixedRequest.execute (/home/electricimp123/.nvm/versions/node/v12.13.0/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/unpackstream.js:41:10)
gnome-shell[1601]:     at UnpackStream.resume (/home/electricimp123/.nvm/versions/node/v12.13.0/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/unpackstream.js:165:30)
gnome-shell[1601]:     at UnpackStream.write (/home/electricimp123/.nvm/versions/node/v12.13.0/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/unpackstream.js:102:10)
gnome-shell[1601]:     at Socket.<anonymous> (/home/electricimp123/.nvm/versions/node/v12.13.0/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/xcore.js:88:21)
gnome-shell[1601]:     at Socket.emit (events.js:189:13)
gnome-shell[1601]:     at addChunk (_stream_readable.js:284:12)
gnome-shell[1601]:     at readableAddChunk (_stream_readable.js:265:11)
gnome-shell[1601]:     at Socket.Readable.push (_stream_readable.js:220:10)
gnome-shell[1601]:     at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
gnome-shell[1601]:   error: 3,
gnome-shell[1601]:   seq: 31,
gnome-shell[1601]:   message: 'Bad window',
gnome-shell[1601]:   badParam: 0,
gnome-shell[1601]:   minorOpcode: 0,
gnome-shell[1601]:   majorOpcode: 21 }

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment]
I just tried with Ubuntu 19.04 and I am unable to reproduce this issue unfortunately. Have you tried resaving your session?

**Comment by johannesjo** [comment]
Thanks for getting back to me. One more question. Is the gnome terminal one of the apps you're trying to restore or not?

**Comment by johannesjo** [comment]
Where you able to solve your issue?

**Comment by electricimp123** [comment]
No, still not resolved. Disabling Wayland didn't help.  config.json looks fine (used xprop and locate to verify).

**Comment by johannesjo** [comment]
Unfortunately I am not able to reproduce this. There are a couple of things you can try: 
* Try running a minimal case (just gnome terminal) and see if the error happens 
* You must use XWayland for gnome terminal.
* check if the gnome terminal command in the config.json can be run from the command line

**Comment by johannesjo** [comment]
I am closing this due to inactivity.
