### ISSUE TITLE
Restore not working with > 1 Gnome Terminal window

### ISSUE THREAD

**Issue by marcelo-gonzalez** [johannesjo/linux-window-session-manager#60]
## Your Environment

* Version used: 3.1.2
* Operating System and version: Debian 10.2
* Desktop Environment: Cinnamon 3.8.8
* Node version: v13.9.0
* List of Applications that are open (lwsm save) or should be opened (lwsm restore): three Gnome terminal sessions, plus chrome and a settings window. But it appears what matters here is that there's > 1 gnome terminal

## Expected Behavior

I have three gnome terminal windows open, and run
$ lwsm save
 close windows...
$ lwsm restore
expect old windows to pop up...

## Current Behavior
This seems to occur with any configuration of windows where there are at least two Gnome terminals open. With only one, everything is fine.

```
$ lwsm save

 Trying alternative guessing approach for "Gnome-terminal".....

 Trying alternative guessing approach for "Gnome-terminal".....

 Trying alternative guessing approach for "Gnome-terminal".....

 Alternative guessing approach for "Gnome-terminal" SUCCESS -> /usr/lib/gnome-terminal/gnome-terminal-server

 Alternative guessing approach for "Gnome-terminal" SUCCESS -> /usr/lib/gnome-terminal/gnome-terminal-server

 Alternative guessing approach for "Gnome-terminal" SUCCESS -> /usr/lib/gnome-terminal/gnome-terminal-server
SAVED SESSION: DEFAULT

<close all windows>

$ lwsm restore
Status: "gnome-terminal-server.Gnome-terminal" is running: false 3 0
Status: "gnome-terminal-server.Gnome-terminal" is running: false 3 0
Status: "gnome-terminal-server.Gnome-terminal" is running: false 3 0
Status: "google-chrome.Google-chrome" is running: true 1 0
Status: "cinnamon-settings.py.Cinnamon-settings.py" is running: true 1 0
Waiting for all applications to start...

<hangs ...>
```

Took a peek at ~/.lwsm/sessionData/DEFAULT.json, and this issue is fixed by this patch:

```
@@ -19,7 +19,8 @@
           "width": 1094,
           "height": 1124,
           "simpleName": "Gnome-terminal",
-          "executableFile": "/usr/lib/gnome-terminal/gnome-terminal-server"
+          "executableFile": "org.gnome.Terminal.desktop",
+         "desktopFilePath": "/usr/share/applications/org.gnome.Terminal.desktop"
         },
         {
           "windowId": "0x4600062",
@@ -34,7 +35,8 @@
           "width": 734,
           "height": 458,
           "simpleName": "Gnome-terminal",
-          "executableFile": "/usr/lib/gnome-terminal/gnome-terminal-server"
+          "executableFile": "org.gnome.Terminal.desktop",
+         "desktopFilePath": "/usr/share/applications/org.gnome.Terminal.desktop"
         },
         {
           "windowId": "0x4600070",
@@ -49,7 +51,8 @@
           "width": 734,
           "height": 458,
           "simpleName": "Gnome-terminal",
-          "executableFile": "/usr/lib/gnome-terminal/gnome-terminal-server"
+          "executableFile": "org.gnome.Terminal.desktop",
+         "desktopFilePath": "/usr/share/applications/org.gnome.Terminal.desktop"
```
Am I maybe doing something wrong in the setup? All other desktop apps seem to work okay for me.

Thanks,

-Marcelo

**Comment by johannesjo** [comment]
Some questions:

1. One of the two executableFile or desktopFilePath should be enough. Which of the 2 does the trick for you?
2. Does executing /usr/lib/gnome-terminal/gnome-terminal-server manually from the terminal work?
3. Are you on Wayland by any chance?

**Comment by marcelo-gonzalez** [comment]
1. ahh it's the desktopFilePath that's needed. With only executableFile I get:
```
$ lwsm restore
Generic Error in Main Handler Error: could not load data
    at /usr/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:209:15
    at /usr/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:100:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) Error: could not load data
    at /usr/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:209:15
    at /usr/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:100:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
(node:2146) UnhandledPromiseRejectionWarning: Error: could not load data
    at /usr/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:209:15
    at /usr/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:100:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
(node:2146) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2146) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

2. I get:
```
$ /usr/lib/gnome-terminal/gnome-terminal-server
Failed to register: Unable to acquire bus name 'org.gnome.Terminal'
```

3. nope

**Comment by johannesjo** [comment]
Ok 2. is interesting. Not sure if this is specific to debian or cinamon. Thank you!

What you can do to circumvent this error in the future is to add a permanent default mapping to `~/.lwsm/config.json`:
```
  "WM_CLASS_AND_EXECUTABLE_FILE_MAP": {
    "gnome-terminal-server.Gnome-terminal": "----> insert working executable path for gnome terminal <----",
```

**Comment by marcelo-gonzalez** [comment]
sounds good thanks!
