### ISSUE TITLE
on linux mint mate every running application is being detected as appname.desktop

### ISSUE THREAD

**Issue by elypter** [johannesjo/linux-window-session-manager#9]
maybe thats a mate thing but this makes the script fail because those files do not actually exist

```
locate mate-terminal.desktop { [Error: Command failed: /bin/sh -c locate mate-terminal.desktop
/bin/sh: 1: locate mate-terminal.desktop: not found
]
  killed: false,
  code: 127,
  signal: null,
  cmd: '/bin/sh -c locate mate-terminal.desktop' }
otherCmd: Generic Error { [Error: Command failed: /bin/sh -c locate mate-terminal.desktop
/bin/sh: 1: locate mate-terminal.desktop: not found
]
  killed: false,
  code: 127,
  signal: null,
  cmd: '/bin/sh -c locate mate-terminal.desktop' } Error: Command failed: /bin/sh -c locate mate-terminal.desktop
/bin/sh: 1: locate mate-terminal.desktop: not found

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous(internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
otherCmd: { '0': 
   { [Error: Command failed: /bin/sh -c locate mate-terminal.desktop
   /bin/sh: 1: locate mate-terminal.desktop: not found
   ]
     killed: false,
     code: 127,
     signal: null,
     cmd: '/bin/sh -c locate mate-terminal.desktop' } }
Input Handler Error:  No input for desktop file path for window mate-terminal.Mate-terminal. Please fix this manually in config file for this session in ~/.lwsm/session-name.json undefined
locate mate-terminal.desktop { [Error: Command failed: /bin/sh -c locate mate-terminal.desktop
/bin/sh: 1: locate mate-terminal.desktop: not found
]
  killed: false,
  code: 127,
  signal: null,
  cmd: '/bin/sh -c locate mate-terminal.desktop' }
otherCmd: Generic Error { [Error: Command failed: /bin/sh -c locate mate-terminal.desktop
/bin/sh: 1: locate mate-terminal.desktop: not found
]
  killed: false,
  code: 127,
  signal: null,
  cmd: '/bin/sh -c locate mate-terminal.desktop' } Error: Command failed: /bin/sh -c locate mate-terminal.desktop
/bin/sh: 1: locate mate-terminal.desktop: not found

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous(internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
otherCmd: { '0': 
   { [Error: Command failed: /bin/sh -c locate mate-terminal.desktop
   /bin/sh: 1: locate mate-terminal.desktop: not found
   ]
     killed: false,
     code: 127,
     signal: null,
     cmd: '/bin/sh -c locate mate-terminal.desktop' } }
Input Handler Error:  No input for desktop file path for window mate-terminal.Mate-terminal. Please fix this manually in config file for this session in ~/.lwsm/session-name.json undefinedlocate xed.desktop { [Error: Command failed: /bin/sh -c locate xed.desktop
/bin/sh: 1: locate xed.desktop: not found
]
  killed: false,
  code: 127,
  signal: null,
  cmd: '/bin/sh -c locate xed.desktop' }
otherCmd: Generic Error { [Error: Command failed: /bin/sh -c locate xed.desktop
/bin/sh: 1: locate xed.desktop: not found
]
  killed: false,
  code: 127,
  signal: null,
  cmd: '/bin/sh -c locate xed.desktop' } Error: Command failed: /bin/sh -c locate xed.desktop
/bin/sh: 1: locate xed.desktop: not found

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous(internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
otherCmd: { '0': 
   { [Error: Command failed: /bin/sh -c locate xed.desktop
   /bin/sh: 1: locate xed.desktop: not found
   ]
     killed: false,
     code: 127,
     signal: null,
     cmd: '/bin/sh -c locate xed.desktop' } }
Input Handler Error:  No input for desktop file path for window xed.Xed. Please fix this manually in config file for this session in ~/.lwsm/session-name.json undefined
SAVED SESSION: DEFAULT
niemand@akara ~ $ 
```

**Comment by johannesjo** [comment]
Thanks for reporting! I'll look into it as soon as I can.

**Comment by johannesjo** [comment]
Could you try installing the `locate` command by `sudo apt-get install mlocate` and try again?

**Comment by elypter** [comment]
it tells me that i already have the newest version

> »mlocate« ist bereits die neuste Version (0.26-1ubuntu2).

**Comment by johannesjo** [comment]
And what about `/bin/sh`?

**Comment by johannesjo** [comment]
Also what's the output of `locate sh`?

**Comment by elypter** [comment]
the first opens a shell and the second prints out files containing sh for several seconds

**Comment by elypter** [comment]
my installed version is 4.2.6~dfsg-1ubuntu4.1 for nodejs and nodejs-legacy which i had to install because i got an error about a missing node binary

**Comment by johannesjo** [comment]
Ah ok. I think misunderstood the problem. Are `mate-terminal` and `xed` actual applications?

**Comment by elypter** [comment]
yes, those are the default terminal emulator and text editor

**Comment by johannesjo** [comment]
What you always can do is adding the actual .desktop file names to the `WM_CLASS_AND_EXECUTABLE_FILE_MAP` property in `~/.lwsm/config.json`. You can find out the property name (e.g. "Navigator.Firefox" for "firefox.desktop" in the default config) via `wmctrl -lpGxu -v` for example. Would be cool if you could share, what worked in the end for you.

Another easier option would be to edit `~/.lwsm/sessionData/DEFAULT.json` and just add the correct path to the desktop file there.
