### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Command failed: cat /proc/undefined/cmdline

### ISSUE THREAD

**Issue by Robert-Riedl** [johannesjo/linux-window-session-manager#99]
Sessions aren't saved, throw errors and just hangs

## :pancakes: Action version

lwsm 4.0.5 

## :tophat: workflow configuration

Your workflow configuration

## Steps To Reproduce

1. open terminal
2. type lwsm save

## :police_car: Expected behavior

Session should be saved

## :heavy_plus_sign: Additional context

Nodejs is installed properly and I'm not on wayland

`
```
ERR: findDesktopFile() cant find file "Navigator.desktop"! Searched desktopFileLocations: [ '{home}/.local/share/applications',
  '{home}/.gnome/apps',
  '/usr/share/applications',
  '/usr/local/share/applications',
  '/usr/share/app-install',
  '{home}/.config/autostart',
  '/var/lib/snapd/desktop/applications',
  '/var/lib/flatpak/app',
  '/var/lib/flatpak/exports/share/applications',
  '{home}/.local/share/flatpak/exports/share/applications',
  '/snap/bin',
  '{home}/.local/share/applications',
  '{home}/.gnome/apps',
  '/usr/share/applications',
  '/usr/local/share/applications',
  '/usr/share/app-install',
  '{home}/.config/autostart',
  '/var/lib/snapd/desktop/applications',
  '/var/lib/flatpak/app',
  '/var/lib/flatpak/exports/share/applications',
  '{home}/.local/share/flatpak/exports/share/applications',
  '/snap/bin' ]
[...]
ERR _guessFilePath() { Error: Command failed: cat /proc/undefined/cmdline
cat: /proc/undefined/cmdline: No such file or directory

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'cat /proc/undefined/cmdline' }
Generic Error in Main Handler { Error: Command failed: cat /proc/undefined/cmdline
cat: /proc/undefined/cmdline: No such file or directory
[...]
(node:20542) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:20542) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 5)

 Alternative guessing approach for "firefox" SUCCESS -> /usr/lib/firefox/firefox

```
`

**Comment by typoworx-de** [comment]
Got the same issue

**Comment by typoworx-de** [comment]
Any news on this? I'm getting the error for example here:
```
Alternative guessing approach for "TelegramDesktop" SUCCESS -> /opt/telegram/Telegram
ERR _guessFilePath() Error: Command failed: cat /proc/undefined/cmdline
cat: /proc/undefined/cmdline: No such file or directory
```

/opt/telegram/Telegram actually exists and it is a regular linux-binary
